# Generated by Django 5.2.4 on 2025-07-19 07:54

import django.db.models.deletion
import posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careermilestone',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='endorsement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='endorsement',
            name='endorsed',
        ),
        migrations.RemoveField(
            model_name='endorsement',
            name='endorser',
        ),
        migrations.RemoveField(
            model_name='endorsement',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='mentorshipbooking',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='mentorshipbooking',
            name='student',
        ),
        migrations.RemoveField(
            model_name='mentorshipslot',
            name='post',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='postattachment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='visibility',
        ),
        migrations.AddField(
            model_name='post',
            name='application_deadline',
            field=models.DateField(blank=True, help_text='Optional: Deadline for jobs/internships', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='external_link',
            field=models.URLField(blank=True, help_text='Any relevant link (form, website, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Moderation flag (optional)'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, help_text='Event/Job location if applicable', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=posts.models.upload_to),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Admin feature to pin important posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('internship', 'Internship Opportunity'), ('job', 'Job Opening'), ('event', 'Event'), ('seminar', 'Seminar / Webinar'), ('announcement', 'General Announcement'), ('achievement', 'Achievement'), ('discussion', 'Discussion'), ('resource', 'Resource Sharing')], default='announcement', max_length=50),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
        ),
        migrations.DeleteModel(
            name='AlumniHighlight',
        ),
        migrations.DeleteModel(
            name='CareerMilestone',
        ),
        migrations.DeleteModel(
            name='Endorsement',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='MentorshipBooking',
        ),
        migrations.DeleteModel(
            name='MentorshipSlot',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='PostAttachment',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for searchability', max_length=255),
        ),
    ]
