# Generated by Django 5.2.4 on 2025-07-16 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='batch_year',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_completed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='school',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='specialization',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('alumni', 'Alumni'), ('student', 'Student')], default='student', max_length=50),
        ),
    ]
