# Generated by Django 5.2.4 on 2025-07-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_badges_customuser_batch_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
