# Generated by Django 5.2.4 on 2025-07-22 06:24

import django.db.models.deletion
import events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('seminar', 'Seminar'), ('webinar', 'Webinar'), ('reunion', 'Alumni Reunion'), ('networking', 'Networking Meetup'), ('workshop', 'Workshop'), ('career', 'Career Talk'), ('other', 'Other')], default='other', max_length=50)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to=events.models.event_media_upload_to)),
                ('max_seats', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('registered_users', models.ManyToManyField(blank=True, related_name='joined_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
